### ISSUE TITLE
Fee Distribution not loading when Custom server used

### ISSUE THREAD

**Issue by ponthief** [aeonBTC/Mempal#2]
Fee Distribution displays "Loading..." all the time when connected to the local Mempool instance.
(All other stats are displaying fine.) 
Local Mempool instance displays all the stats in the browser as the one on mempool.space.
(v.1.3)

**Comment by aeonBTC** [comment]
I am aware of this problem. Its an issue with mempool.space's API for locally hosted instances.
It specifically relates to: https://mempool.space/api/mempool 

The fee histogram field populates just fine on mempool.space, but if you check the same API call for your local instance it wont populate.
 
I have brought it to their attention and hopefully they will fix it soon.

**Comment by aeonBTC** [comment]
For now this issue has been mitigated with a workaround in [v1.4.0](https://github.com/aeonBTC/Mempal/releases/tag/v1.4.0).
