### ISSUE TITLE
Add purge value

### ISSUE THREAD

**Issue by rottenwheel** [aeonBTC/Mempal#3]
Mempool space or some other site always listed the purge value. You must pay X amount minimum, otherwise mempool will reject your tx. Would be nice to have it as the last line of next block, in 1 day estimated times, or even its own separate section if need be.

Minimalistic application, yet useful! Thanks for your work.

**Comment by aeonBTC** [comment]
As I understand it, its very rare to have your transaction completely purged anymore. Reason being is because many nodes and miners set their mempool size much higher than 300MB. I've personally had transactions confirm after many months of high fees, despite it being below the purge threshold.

**Comment by rottenwheel** [comment]
...is that a yes or a no? :-P Helps us cheapos just pay enough to get in, no matter how long the wait will be.

**Comment by aeonBTC** [comment]
My point is that there really is no purge level anymore. The absolute minimum is 1 sat/vB and it could sit in a miners mempool for years and never be purged. If you wanted it to confirm eventually RBF would be the best option.

**Comment by rottenwheel** [comment]
There is, otherwise the value wouldn't be shown. Mempool gets busy, purge number goes higher, mempool is not busy, it goes to 1 sat. 3-5 sats, so on. There are people who don't care about getting confirmations quick.

Let's agree to disagree, will keep using the browser. Thanks!

**Comment by aeonBTC** [comment]
> There is, otherwise the value wouldn't be shown. Mempool gets busy, purge number goes higher, mempool is not busy, it goes to 1 sat. 3-5 sats, so on. There are people who don't care about getting confirmations quick.
> 
> Let's agree to disagree, will keep using the browser. Thanks!

Last year the mempool.space mempool was 500+ MB and no transactions were being purged, this is because on their node they set the maxmempool flag much higher than the default of 300MB. Most miners follow this same configuration as well so they can maximize fee profits.

My point is that the purge limit is not universal number that can be known, because each node can set a their own maxmempool size. If people don't mind waiting for confirmation simply set your fee to 1 sat/vb and use RBF to bump if need be.

**Comment by aeonBTC** [comment]
@rottenwheel I encourage you to go to mempool.space, you will see that even though they are claiming txs with fees less than 1.49 sat/vB are being purged you can still find many txs with fees below that limit (e.g. https://mempool.space/tx/b1dc676bb5e34f6492019fc0a2e30e4104f33c9f37ed4acd32c7eb806ec69bec) that are not being purged from their mempool.

I understand why you might want this feature but it is only useful if everyone sets their maxmempool to the same 300MB size and these days many nodes, especially miners, have much higher maxmempool than the 300MB default.

**Comment by rottenwheel** [comment]
Lol, just drop it man. Thanks for the information and input though. Cheers.

**Comment by aeonBTC** [comment]
No worries, im happy to help people understand mempool dynamics as they are, rather than relying on bad metrics in regards to fee estimation.
